### ISSUE TITLE
Should the "business logic" (electrum interactions) be a standalone library?

### ISSUE THREAD

**Issue by DukeFerdinand** [kevacoin-project/keva_ws#1]
First off, really like the idea of making an easy-to-deploy keva implementation. I think that's why we haven't seen mass adoption yet: devs can't really do a lot on-chain :(

However, I believe it would make more sense to completely separate the websocket library from the UI/UX. Speaking as a dev who is super interested in using Keva to power some sites, I'd personally think that a library would be _much_ more useful for a wider audience than a simple React site.

We can still (and should still) have the React site for demo purposes, but I'd still argue in favor of extracting out the interactions into a JS/TS powered library so you're not locked into extracting all of that yourself. I'll try to get a demo up this week so you can see what I mean, otherwise please take a look at my repo for what I mean: https://github.com/DukeFerdinand/kevacoin-js :)

**Comment by kevacoin-project** [comment]
Thanks for the suggestion and we like it! We will convert ElectrumX API into a standalone library, while keep this React demo/plugin for easy web integration (e.g. like Twitter's web plugin).

**Comment by DukeFerdinand** [comment]
@kevacoin-project Glad to hear it! Let me know if you'd like some collaboration there, as I'd love to setup a TypeScript workflow for the library. TS would offer a much better developer workflow for the library as well as people using the library in their own JS projects :)

**Comment by kevacoin-project** [comment]
@DukeFerdinand just add you to the new repo "https://github.com/kevacoin-project/keva-api-js". I would love to use Typescript too, but would definitely need some help on Typescript.

Please feel free to contribute to the project, and any help will be much appreciated.
To test the project:

```
npm install
npm run test
```
Please take a look at `index.test.js` to see how to call our APIs.

**Comment by DukeFerdinand** [comment]
Heck yeah, I'll take a look later and see what I can get setup 😎

**Comment by kevacoin-project** [comment]
The project has been updated to use the new "keva-api-js" module for the ElectrumX related API:
https://github.com/kevacoin-project/keva_ws/commit/89b2dc45f85aef7f66a8e1e80009c6e2949ed7dc
